excluded:
  - Pods
  - vendor

disabled_rules:
  - identifier_name        # Only allows names with 3-40 characters
  - switch_case_alignment  # Clashes with .idea formatting
  - file_length            # Test files are allowed to grow large
  - type_body_length       # Again, test files.
