excluded:
  - Pods
  - vendor

disabled_rules:
  - identifier_name        # Only allows names with 3-40 characters
  - switch_case_alignment  # Clashes with .idea formatting
  - file_length            # Test files are allowed to grow large
  - type_body_length       # Again, test files.
  - function_body_length   # And again, test files.
  - cyclomatic_complexity  # Will be handled during code review
  - type_name              # Necessary for SwiftUI previews
  - nesting                # Nesting is perfect for grouping
  - todo                   # We can't implement everything at once
  - multiple_closures_with_trailing_closure # This is recommended with SwiftUI