name: FTMS-iOS

options:
  bundleIdPrefix: "uk.co.waterrower"

settings:
  DEVELOPMENT_TEAM: CMQS4E74X4

targets:

  FTMS-iOS-Framework:
    type: framework
    platform: iOS
    sources: [FTMS-iOS-Framework]
    scheme:
      testTargets:
        - FTMS-iOS-Framework-Tests

  FTMS-iOS-Framework-Tests:
    type: bundle.unit-test
    platform: iOS
    sources: [FTMS-iOS-Framework-Tests]
    dependencies:
      - target: FTMS-iOS-Framework
