name: FTMS-iOS

options:
  bundleIdPrefix: "uk.co.waterrower"

settings:
  DEVELOPMENT_TEAM: CMQS4E74X4

targets:
  FTMS-iOS-Framework:
    type: framework
    platform: iOS
    sources: [FTMS-iOS-Framework]
