name: Test

on: pull_request

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Swift Test
        run: swift test
      - name: Pod lib lint
        run: pod lib lint --verbose
      - name: XCodeBuild
        run: xcodebuild -workspace iOS\ Example/iOS\ Example.xcworkspace -scheme "iOS Example" build CODE_SIGNING_REQUIRED=NO
